# Generated by Django 3.2.4 on 2023-08-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='email',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='universities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
