# Generated by Django 3.2.4 on 2023-08-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230807_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='reapplied',
            field=models.BooleanField(default=True),
        ),
    ]
