# Generated by Django 3.2.4 on 2023-08-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_studentdata_reapplied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionOne', models.TextField(default="<br />I would like to {{ quality.recommend }} recommend <b>{{ student.name }}</b> for admission to the graduate program at your university. I have known {{ student.firstname }} for about {{ student.years_taught }} now as an undergraduate student in {{ student.std.program }} Engineering. {% if student.is_pro == 'Yes' %} Moreover, I was the supervisor for his final year project. {% endif %} {% if value %} I taught him {{ subject }}. {% else %} I taught him {% for item in subjects %} {{ item }}, {% endfor %} and {{ subject }}. {% endif %}")),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.teacherinfo')),
            ],
        ),
    ]
