# Generated by Django 3.2.4 on 2023-08-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='sectionOne',
            field=models.TextField(default="<br />I would like to {{ quality.recommend }} recommend <b>{{ student.name }}</b> for admission to the graduate program at your university. I have known {{ student.firstname }} for about {{ student.years_taught }} now as an undergraduate student in {{ student.std.program }} Engineering. {% if student.is_pro == 'Yes' %} Moreover, I was the supervisor for his final year project. {% endif %} {% if value %} I taught him {{ subject }}. {% else %} I taught him  {% for item in subjects %} {{ item }}, {% endfor %} and {{ subject }}. {% endif %}"),
        ),
    ]
