# Generated by Django 3.2.4 on 2023-08-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230814_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='sectionOne',
        ),
        migrations.RemoveField(
            model_name='template',
            name='sectionTwo',
        ),
    ]
