# Generated by Django 3.2.4 on 2023-08-14 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
